### ISSUE TITLE
Supported input file formats

### ISSUE THREAD

**Issue by aminakur** [OluwadareLab/ParticleChromo3D_Plus#3]
Thank you for developing the tool!

I tried to upload a .hic file on the web version of the tool. I am not sure it went through. 
So, are the .hic matrices supported? What about .cool/.mcool?
Does a .hic matrix need to be a single chromosome or genome-wide would be supported?

**Comment by OluwadareLab** [comment]
Thanks for using our tool. 

For simplicity and easier processing,  as noted on the website, the particlechromo3D tool only accepts tab-separated square matrices for a single chromosome.   So, you will need to extract your desired matrix from the .hic file before you can use our tool for the reconstruction. Also, genome-wide reconstruction is not currently supported.
